### ISSUE TITLE
Add flags to skip/pre-answer questions

### ISSUE THREAD

**Issue by BrendanNeufeld** [Jam3/nyg-ui-generator#5]
e.g.
`nyg nyg-ui-generator --type react` //will skip component type prompt

Essentially create a flag for every option that makes sense. Defaults and warnings should also be set up for flags that contradict each other.

Assumption: you have already generated a component and you want to publish
e.g. `nyg nyg-ui-generator --mode publish --type react`
- you are trying to pick the type of an already generated component.

Maybe a warning shows and the contradicting flags are ignore.

**Comment by realdeemy** [comment]
Done
